export const countriesData = {
  southkorea: {
    lat: 35.907757,
    lng: 127.766922,
    name: 'South Korea',
    lowername: 'southkorea',
    code: 'kr',
    info: '수도는 서울특별시로 인구는 5163만명이다.',
    airport: 'ICN',
    money: 'KRW',
    capital: 'Seoul',
  },
  usa: {
    lat: 39.891275,
    lng: -101.375893,
    name: 'USA',
    lowername: 'usa',
    code: 'us',
    info: '미국의 수도는 워싱턴 D.C.입니다.',
    airport: 'JFK',
    money: 'USD',
    capital: 'Washington',
  },
  japan: {
    lat: 36.204824,
    lng: 138.252924,
    name: 'Japan',
    lowername: 'japan',
    code: 'jp',
    info: '일본의 수도는 도쿄입니다.',
    airport: 'NRT',
    money: 'JPY',
    capital: 'Tokyo',
  },
  china: {
    lat: 35.86166,
    lng: 104.195397,
    name: 'China',
    lowername: 'china',
    code: 'cn',
    info: '중국의 수도는 베이징입니다.',
    airport: 'PEK',
    money: 'CNY',
    capital: 'Beijing',
  },
  unitedkingdom: {
    lat: 55.378051,
    lng: -3.435973,
    name: 'United Kingdom',
    lowername: 'unitedkingdom',
    code: 'gb',
    info: '영국의 수도는 런던입니다.',
    airport: 'LHR',
    money: 'GBP',
    capital: 'London',
  },
  russia: {
    lat: 61.52401,
    lng: 105.318756,
    name: 'Russia',
    lowername: 'russia',
    code: 'ru',
    info: '러시아의 수도는 모스크바입니다.',
    airport: 'SVO',
    money: 'RUB',
    capital: 'Moscow',
  },
  australia: {
    lat: -25.274398,
    lng: 133.775136,
    name: 'Australia',
    lowername: 'australia',
    code: 'au',
    info: '호주의 수도는 캔버라입니다.',
    airport: 'SYD',
    money: 'AUD',
    capital: 'Canberra',
  },
  canada: {
    lat: 56.130366,
    lng: -106.346771,
    name: 'Canada',
    lowername: 'canada',
    code: 'ca',
    info: '캐나다의 수도는 오타와입니다.',
    airport: 'YYZ',
    money: 'CAD',
    capital: 'Ottawa',
  },
  germany: {
    lat: 51.165691,
    lng: 10.451526,
    name: 'Germany',
    lowername: 'germany',
    code: 'ge',
    info: '독일의 수도는 베를린입니다.',
    airport: 'FRA',
    money: 'EUR',
    capital: 'Berlin',
  },
  france: {
    lat: 44.165691,
    lng: 1.451526,
    name: 'France',
    lowername: 'france',
    code: 'fr',
    info: '프랑스',
    airport: 'CDG',
    money: 'EUR',
    capital: 'Paris',
  },
};
