export const countriesData = {
  france: {
    lat: 46.603354,
    lng: 1.888334,
    name: 'France',
    lowername: 'france',
    code: 'fr',
    info: '프랑스는 아름다운 자연경관과 세계적인 예술, 문화 명소로 유명합니다.',
    airport: 'CDG',
    money: 'EUR',
    capital: 'Paris',
    attractions: [
      {
        image: '/countries/france/Eiffel Tower.jpg',
        name: 'Eiffel Tower',
        description: '프랑스 파리의 상징적인 랜드마크입니다.',
      },
      {
        image: '/countries/france/Louvre Museum.jpg',
        name: 'Louvre Museum',
        description: '세계에서 가장 유명한 미술관 중 하나입니다.',
      },
      {
        image: '/countries/france/Mont Saint-Michel.png',
        name: 'Mont Saint-Michel',
        description: '프랑스의 유명한 섬 수도원입니다.',
      },
    ],
  },
  italy: {
    lat: 41.87194,
    lng: 12.56738,
    name: 'Italy',
    lowername: 'italy',
    code: 'it',
    info: '이탈리아는 역사적인 유적지와 맛있는 음식으로 유명한 관광지입니다.',
    airport: 'FCO',
    money: 'EUR',
    capital: 'Rome',
    attractions: [
      {
        image: '/countries/italy/Colosseum.jpg',
        name: 'Colosseum',
        description: '고대 로마의 원형 경기장입니다.',
      },
      {
        image: '/countries/italy/Venice Canals.jpg',
        name: 'Venice Canals',
        description: '물의 도시 베니스의 유명한 운하입니다.',
      },
      {
        image: '/countries/italy/Leaning Tower of Pisa.jpg',
        name: 'Leaning Tower of Pisa',
        description: '피사의 기울어진 탑입니다.',
      },
    ],
  },
  singapore: {
    lat: 1.352083,
    lng: 103.819836,
    name: 'Singapore',
    lowername: 'singapore',
    code: 'sg',
    info: '싱가포르는 현대적인 도시와 풍부한 문화가 어우러진 여행지입니다.',
    airport: 'SIN',
    money: 'SGD',
    capital: 'Singapore',
    attractions: [
      {
        image: '/countries/singapore/Marina Bay Sands.jpg',
        name: 'Marina Bay Sands',
        description: '싱가포르의 대표적인 랜드마크 호텔입니다.',
      },
      {
        image: '/countries/singapore/Gardens by the Bay.jpg',
        name: 'Gardens by the Bay',
        description: '싱가포르의 유명한 정원입니다.',
      },
      {
        image: '/countries/singapore/Sentosa Island.jpg',
        name: 'Sentosa Island',
        description: '싱가포르의 유명한 관광지입니다.',
      },
    ],
  },
  spain: {
    lat: 40.463667,
    lng: -3.74922,
    name: 'Spain',
    lowername: 'spain',
    code: 'es',
    info: '스페인은 다양한 문화와 축제로 유명한 나라입니다.',
    airport: 'MAD',
    money: 'EUR',
    capital: 'Madrid',
    attractions: [
      {
        image: '/countries/spain/Sagrada Familia.png',
        name: 'Sagrada Familia',
        description: '바르셀로나의 유명한 성당입니다.',
      },
      {
        image: '/countries/spain/Alhambra.jpg',
        name: 'Alhambra',
        description: '그라나다에 있는 유명한 궁전입니다.',
      },
      {
        image: '/countries/spain/Park Güell.jpg',
        name: 'Park Güell',
        description: '바르셀로나의 유명한 공원입니다.',
      },
    ],
  },
  turkey: {
    lat: 38.963745,
    lng: 35.243322,
    name: 'Turkey',
    lowername: 'turkey',
    code: 'tr',
    info: '튀르키예는 풍부한 역사와 아름다운 해안선으로 유명합니다.',
    airport: 'IST',
    money: 'TRY',
    capital: 'Ankara',
    attractions: [
      {
        image: '/countries/turkey/Hagia Sophia.jpg',
        name: 'Hagia Sophia',
        description: '이스탄불의 유명한 박물관 및 모스크입니다.',
      },
      {
        image: '/countries/turkey/Cappadocia.jpg',
        name: 'Cappadocia',
        description: '풍경이 아름다운 지역입니다.',
      },
      {
        image: '/countries/turkey/Pamukkale.jpg',
        name: 'Pamukkale',
        description: '터키의 유명한 온천지입니다.',
      },
    ],
  },
  australia: {
    lat: -25.274398,
    lng: 133.775136,
    name: 'Australia',
    lowername: 'australia',
    code: 'au',
    info: '호주는 자연 경관과 독특한 야생 동물로 유명합니다.',
    airport: 'SYD',
    money: 'AUD',
    capital: 'Canberra',
    attractions: [
      {
        image: '/countries/australia/Sydney Opera House.jpg',
        name: 'Sydney Opera House',
        description: '시드니의 상징적인 오페라 하우스입니다.',
      },
      {
        image: '/countries/australia/Great Barrier Reef.jpg',
        name: 'Great Barrier Reef',
        description: '세계에서 가장 큰 산호초입니다.',
      },
      {
        image: '/countries/australia/Uluru.jpg',
        name: 'Uluru',
        description: '호주의 유명한 바위산입니다.',
      },
    ],
  },
  japan: {
    lat: 36.204824,
    lng: 138.252924,
    name: 'Japan',
    lowername: 'japan',
    code: 'jp',
    info: '일본은 전통과 현대가 공존하는 매력적인 나라입니다.',
    airport: 'NRT',
    money: 'JPY',
    capital: 'Tokyo',
    attractions: [
      {
        image: '/countries/japan/Mount Fuji.jpg',
        name: 'Mount Fuji',
        description: '일본의 상징적인 산입니다.',
      },
      {
        image: '/countries/japan/Kyoto Temples.jpg',
        name: 'Kyoto Temples',
        description: '교토의 전통적인 사원들입니다.',
      },
      {
        image: '/countries/japan/Tokyo Tower.jpg',
        name: 'Tokyo Tower',
        description: '도쿄의 유명한 타워입니다.',
      },
    ],
  },
  vietnam: {
    lat: 14.058324,
    lng: 108.277199,
    name: 'Vietnam',
    lowername: 'vietnam',
    code: 'vn',
    info: '베트남은 아름다운 자연과 풍부한 문화로 유명한 나라입니다.',
    airport: 'HAN',
    money: 'VND',
    capital: 'Hanoi',
    attractions: [
      {
        image: '/countries/vietnam/Halong Bay.jpg',
        name: 'Halong Bay',
        description: '아름다운 해안 경관으로 유명한 베트남의 명소입니다.',
      },
      {
        image: '/countries/vietnam/Cu Chi Tunnels.jpg',
        name: 'Cu Chi Tunnels',
        description: '베트남 전쟁의 중요한 유적지입니다.',
      },
      {
        image: '/countries/vietnam/Hoi An.jpg',
        name: 'Hoi An',
        description: '역사적인 매력을 지닌 베트남의 도시입니다.',
      },
    ],
  },
  thailand: {
    lat: 15.870032,
    lng: 100.992541,
    name: 'Thailand',
    lowername: 'thailand',
    code: 'th',
    info: '태국은 환상적인 해변과 맛있는 음식으로 유명합니다.',
    airport: 'BKK',
    money: 'THB',
    capital: 'Bangkok',
    attractions: [
      {
        image: '/countries/thailand/Grand Palace.webp',
        name: 'Grand Palace',
        description: '방콕에 위치한 태국 왕궁입니다.',
      },
      {
        image: '/countries/thailand/Phuket.webp',
        name: 'Phuket',
        description: '태국의 유명한 섬 휴양지입니다.',
      },
      {
        image: '/countries/thailand/Chiang Mai.jpg',
        name: 'Chiang Mai',
        description: '태국 북부의 문화 도시입니다.',
      },
    ],
  },
  philippines: {
    lat: 12.879721,
    lng: 121.774017,
    name: 'Philippines',
    lowername: 'philippines',
    code: 'ph',
    info: '필리핀은 아름다운 섬들과 다양한 해양 활동으로 유명합니다.',
    airport: 'MNL',
    money: 'PHP',
    capital: 'Manila',
    attractions: [
      {
        image: '/countries/philippines/Boracay.jpg',
        name: 'Boracay',
        description: '필리핀의 유명한 섬입니다.',
      },
      {
        image: '/countries/philippines/Chocolate Hills.jpg',
        name: 'Chocolate Hills',
        description: '독특한 지형으로 유명한 필리핀의 명소입니다.',
      },
      {
        image: '/countries/philippines/Puerto Princesa.jpg',
        name: 'Puerto Princesa',
        description: '아름다운 지하강이 있는 필리핀의 자연 경관입니다.',
      },
    ],
  },
  china: {
    lat: 35.86166,
    lng: 104.195397,
    name: 'China',
    lowername: 'china',
    code: 'cn',
    info: '중국은 풍부한 역사와 다양한 문화 유산으로 유명합니다.',
    airport: 'PEK',
    money: 'CNY',
    capital: 'Beijing',
    attractions: [
      {
        image: '/countries/china/Great Wall of China.webp',
        name: 'Great Wall of China',
        description: '세계적으로 유명한 중국의 만리장성입니다.',
      },
      {
        image: '/countries/china/Forbidden City.webp',
        name: 'Forbidden City',
        description: '베이징에 위치한 고대 궁궐입니다.',
      },
      {
        image: '/countries/china/Terracotta Army.jpg',
        name: 'Terracotta Army',
        description: '시안에 있는 고대 중국의 유적지입니다.',
      },
    ],
  },
  brazil: {
    lat: -14.235004,
    lng: -51.92528,
    name: 'Brazil',
    lowername: 'brazil',
    code: 'br',
    info: '브라질은 아름다운 해변과 열정적인 카니발로 유명합니다.',
    airport: 'GRU',
    money: 'BRL',
    capital: 'Brasilia',
    attractions: [
      {
        image: '/countries/brazil/Christ the Redeemer.webp',
        name: 'Christ the Redeemer',
        description: '리우데자네이루의 상징적인 동상입니다.',
      },
      {
        image: '/countries/brazil/Iguazu Falls.jpg',
        name: 'Iguazu Falls',
        description: '브라질과 아르헨티나 국경에 위치한 아름다운 폭포입니다.',
      },
      {
        image: '/countries/brazil/Amazon Rainforest.jpg',
        name: 'Amazon Rainforest',
        description: '세계에서 가장 큰 열대우림입니다.',
      },
    ],
  },
  argentina: {
    lat: -38.416097,
    lng: -63.616672,
    name: 'Argentina',
    lowername: 'argentina',
    code: 'ar',
    info: '아르헨티나는 멋진 자연경관과 풍부한 문화로 유명합니다.',
    airport: 'EZE',
    money: 'ARS',
    capital: 'Buenos Aires',
    attractions: [
      {
        image: '/countries/argentina/Perito Moreno Glacier.jpg',
        name: 'Perito Moreno Glacier',
        description: '지구에서 가장 아름다운 빙하',
      },
      {
        image: '/countries/argentina/Patagonia.webp',
        name: 'Patagonia',
        description: '아르헨티나 남부의 아름다운 자연경관입니다.',
      },
      {
        image: '/countries/argentina/Buenos Aires.jpeg',
        name: 'Buenos Aires',
        description:
          '아르헨티나의 수도로서 풍부한 문화와 역사를 지닌 도시입니다.',
      },
    ],
  },
  peru: {
    lat: -9.189967,
    lng: -75.015152,
    name: 'Peru',
    lowername: 'peru',
    code: 'pe',
    info: '페루는 고대 잉카 문명과 마추픽추로 유명합니다.',
    airport: 'LIM',
    money: 'PEN',
    capital: 'Lima',
    attractions: [
      {
        image: '/countries/peru/Machu Picchu.webp',
        name: 'Machu Picchu',
        description: '고대 잉카 문명의 잔재입니다.',
      },
      {
        image: '/countries/peru/Sacred Valley.webp',
        name: 'Sacred Valley',
        description: '잉카 문명의 중심지였던 지역입니다.',
      },
      {
        image: '/countries/peru/Lake Titicaca.jpg',
        name: 'Lake Titicaca',
        description: '페루와 볼리비아 국경에 위치한 호수입니다.',
      },
    ],
  },
  chile: {
    lat: -35.675147,
    lng: -71.542969,
    name: 'Chile',
    lowername: 'chile',
    code: 'cl',
    info: '칠레는 다양하고 독특한 자연경관으로 유명합니다.',
    airport: 'SCL',
    money: 'CLP',
    capital: 'Santiago',
    attractions: [
      {
        image: '/countries/chile/Atacama Desert.jpg',
        name: 'Atacama Desert',
        description: '세계에서 가장 건조한 사막입니다.',
      },
      {
        image: '/countries/chile/Easter Island.jpg',
        name: 'Easter Island',
        description: '유명한 모아이 석상이 있는 섬입니다.',
      },
      {
        image: '/countries/chile/Torres del Paine.jpg',
        name: 'Torres del Paine',
        description: '칠레 남부의 국립공원입니다.',
      },
    ],
  },
  colombia: {
    lat: 4.570868,
    lng: -74.297333,
    name: 'Colombia',
    lowername: 'colombia',
    code: 'co',
    info: '콜롬비아는 풍부한 문화와 아름다운 자연으로 유명합니다.',
    airport: 'BOG',
    money: 'COP',
    capital: 'Bogota',
    attractions: [
      {
        image: '/countries/colombia/Castillo San Felipe de Barajas.jpg',
        name: 'Castillo San Felipe de Barajas',
        description: '카르타헤나에 있는 역사적인 성입니다.',
      },
      {
        image: '/countries/colombia/Coffee Cultural Landscape.jpg',
        name: 'Coffee Cultural Landscape',
        description: '콜롬비아의 유명한 커피 생산지입니다.',
      },
      {
        image: '/countries/colombia/Tayrona National Park.jpg',
        name: 'Tayrona National Park',
        description: '콜롬비아의 아름다운 자연경관을 자랑하는 국립공원입니다.',
      },
    ],
  },
};
